# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
generate:
  echo5-server: true
  client: true
  models: true
  strict-server: true
output: api.gen.go

output-options:
  name-normalizer: ToCamelCaseWithInitialisms